### ISSUE TITLE
It doesn't work correctly with Markdown

### ISSUE THREAD

**Issue by MikeC-Cn** [the-turk/flarum-mathren#28]
If I use ```$(x,y)$```,it will be rendered [imath](x,y)[/imath],not what it should be rendered like.

**Comment by hasan-ozbey** [comment]
This happens because we're replacing `$...$` or any alias delimiter with their BBCode representation (`[imath]...[/imath]` for this case) on the fly.

See https://github.com/s9e/TextFormatter/issues/167

While the `TextFormatter` lib owner thinking a solution for this, you can add a blank space after first delimiter as a work-around.

**Comment by hasan-ozbey** [comment]
from now on we're using [explicitly paired](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/) BBCodes with numeric suffix being **0**. Thus, any alias delimiter will be replaced with suffixed BBCodes (like `[imath:0]...[/imath:0]`) on the fly.
