### ISSUE TITLE
failed to work with flarum 1.5.0

### ISSUE THREAD

**Issue by frankli0324** [the-turk/flarum-mathren#38]
Flarum core 1.5.0
PHP version: 7.4.30
the-turk-mathren  1.0.7

when enabled, the `forum.js` failed to generate properly.

```js
var functionCache = {
		...
        "if(typeof katex!=='undefined')katex.render(this.innerText, this, {{\"fleqn\":false,\"leqno\":false,\"output\":\"htmlAndMathml\",\"throwOnError\":false,\"errorColor\":\"#cc0000\",\"minRuleThickness\":0.05,\"maxSize\":10,\"maxExpand\":1000,\"macros\":{{}},\"colorIsTextColor\":false,\"displayMode\":false}})": function() {
            if (typeof katex !== 'undefined') katex.render(this.innerText, this, {{ // here
                "fleqn": !1,
                "leqno": !1,
                "output": "htmlAndMathml",
                "throwOnError": !1,
                "errorColor": "#cc0000",
                "minRuleThickness": 0.05,
                "maxSize": 10,
                "maxExpand": 1000,
                "macros": {{}}, // here
                "colorIsTextColor": !1,
                "displayMode": !1
            }})
        },
```

it seems to be generating duplicate parenthesis

**Comment by frankli0324** [comment]
I'm guessing that it's related to https://github.com/s9e/TextFormatter/commit/dd4553f4f9a1b70d71c69857794b41b56a358aa6

did you have the chance to investigate? @the-turk

**Comment by hasan-ozbey** [comment]
I still haven't found the time for investigating this issue but let me cc @JoshyPHP here, as they might lead us to the right direction for fixing this and enlighten us about that commit on their repository.

Here's the related line from my end: https://github.com/the-turk/flarum-mathren/blob/v1.0.0/src/ConfigureTextFormatter.php#L85

**Comment by JoshyPHP** [comment]
I'll try to reproduce with a small independent script but in the meantime if you think the issue is with this specific commit then try again with the latest master. The `htmlspecialchars_decode` was incorrectly leftover from a previous commit and it's now been corrected. If that was the issue, then the lastest master should fix it.

**Comment by JoshyPHP** [comment]
Ok, I think it has something to do with the content of `$options` in that code. Would you mind posting the full *literal* content of the second argument passed to `addCustom()` so that I can run it in isolation? `json_encode()` shouldn't produce double braces so it probably happens somewhere else in the code but I need something I can run in isolation.

For example, the following code works as expected:
```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->enableJavaScript();
$configurator->BBCodes->addCustom(
	'[x]{TEXT}[/x]',
	'<span>
		<xsl:attribute name="data-s9e-livepreview-onupdate">
			doThing({"what": "update"});
		</xsl:attribute>
		<xsl:attribute name="data-s9e-livepreview-onrender">
			doThing({{"what": "render"}});
		</xsl:attribute>
	</span>'
);

$configurator->javascript->exports = ['preview'];
extract($configurator->finalize());

die($js);
```
It produces the following excerpt: (on ~~current master~~ latest release 2.12.0)
```js
let functionCache={"-1409480277":/**@this {!Element}*/function(){
            doThing({"what": "update"});
        },"-927200608":/**@this {!Element}*/function(){
            doThing({{"what": "render"}});
        }};
```

**Comment by frankli0324** [comment]
> then the lastest master should fix it.

yep... seems that upgrading s9e/text-formatter (2.11.5 => 2.12.0) indeed fixed the issue.
