### ISSUE TITLE
Markdown has priority over MathRen

### ISSUE THREAD

**Issue by ghost** [the-turk/flarum-mathren#7]
So, usually Markdown and MathRen play nicely. If you use BBCode, you shouldn't have problems with it. But there is a problem with powers, i.e.

```
[imath]e^test[/imath]
```

will ignore the imath BBCode and make Markdown change it to the LaTeX equivalent of

```
e^{test}
```

![image](https://user-images.githubusercontent.com/60903173/83310930-ecd6dc00-a20d-11ea-8a17-a79c8d5a1e8f.png)

while based on the LaTeX entry, it should display as if it was written like this:

```
e^{t}est
```

![image](https://user-images.githubusercontent.com/60903173/83310958-ffe9ac00-a20d-11ea-8af0-53381affb7a4.png)

---

The problem also seems to be with braces:

```
[imath] U_1 U_{2} [/imath]
[imath] U_{1} U_2 [/imath] 
```

Produces

![image](https://user-images.githubusercontent.com/60903173/83311089-74bce600-a20e-11ea-9a67-161c890f6ae8.png)

instead of

![image](https://user-images.githubusercontent.com/60903173/83311105-83a39880-a20e-11ea-8d16-0c63295177ee.png)

---

This was reproduced on beta-13, both live and local (vanilla). If you want I can add the flarum info output but I don't know why it would be useful when this is a compatibility issue with Markdown. Other Markdown features (such as bold text and italics) don't disrupt this extension.

EDIT: Behaves the same with `[math]` as well.

**Comment by hasan-ozbey** [comment]
Hi, which version are you on?

I can't reproduce any of those issues with **0.3**:

![](https://i.ibb.co/Yp7FDPj/mathren.png)

**Comment by ghost** [comment]
I was on 0.2.7, but updated to 0.3.0 and the issue persists. While the correct output is indeed shown in the preview, once you post it it is still messed up (in the same way) unless you introduce changes (editing and submitting is not enough)

I guess it has to do something with saving? Look at this:

![image](https://user-images.githubusercontent.com/60903173/83312313-1abe1f80-a212-11ea-977c-26b58a033945.png)

![image](https://user-images.githubusercontent.com/60903173/83312332-2a3d6880-a212-11ea-9225-1d1c3ea34aa3.png)

![image](https://user-images.githubusercontent.com/60903173/83312354-480acd80-a212-11ea-9a63-8747c01fe947.png)

(last picture is after saving unchanged post)

---

After I introduce a space to change it, it fixes itself:

![image](https://user-images.githubusercontent.com/60903173/83312398-74bee500-a212-11ea-9331-12d17bdb0fca.png)


Unsure if this should be closed because the issue was fixed with an update, or kept alive because past entries aren't fixed on update.

Also, yeah, I've cleared the cache and restarted the server even. No change.

**Comment by hasan-ozbey** [comment]
Strange enough. Thing is, it shouldn't be a problem even if you on **0.2.x** because the logic is the same - don't mess with the expression between math tags. So if you disable the extension, there still should be hidden (leftover) `[math][/math]` tags in the posts those with an expression. What I'm doing here is tell Flarum to reveal those tags so the KaTeX can see and render them. It was probably a cache issue or something messed with those tags and Flarum was unable to recognize them. I'm not sure, but you can do either one of following checks if you encounter the same problem with different posts again:

- Inspect unrendered element (using browser's dev tools) and check if you can see any strange thing going on with your BBCode tags that you're trying to render with. If you're able to see those BBCode tags in the source, then it **must** be rendered - _hard refresh_ that page.
- Look into that post's raw content (the one with the XML form) from your database and check if you can see the BBCode that you're trying to render with (in other words: look for `[math][/math]` tags around unrendered expression).

**Edit:** I believe when you update that post with some changes in it, Flarum has performed a `redraw()` operation and updated the DOM structure. This might be an explanation for such a strange behaviour.

**Comment by ghost** [comment]
I'm going to test this locally tomorrow, as I have the old MathRen still installed where I can reproduce this. I have fixed all the broken posts on live 😓

**Comment by hasan-ozbey** [comment]
Sorry to hear that but like I said, updating from 0.2.x to 0.3.x should be working without any issues. You've both rendered and unrendered equations on your screenshot so I've no idea what's going wrong there.

I'll keep this open, please keep me updated if any news arise.

**Comment by hasan-ozbey** [comment]
Check out 1.0.0
