### ISSUE TITLE
MathRen is not working in few locations.

### ISSUE THREAD

**Issue by s1-ranjan** [the-turk/flarum-mathren#8]
I have found MathRen is not working in following 4 different locations:
1. Pin discussions to the top of the list.
![1](https://user-images.githubusercontent.com/20767253/83477866-f2545080-a4b1-11ea-8daa-7e6d11fcd9f9.png)
2. In the tag page.
![2](https://user-images.githubusercontent.com/20767253/83477955-2f204780-a4b2-11ea-938e-035f9b24fbe8.png)
3. Under discussion when user is log-in.
![3](https://user-images.githubusercontent.com/20767253/83478005-537c2400-a4b2-11ea-8d1b-8270a459e57a.png)
4. Under Quote and Quote-popup.
![4](https://user-images.githubusercontent.com/20767253/83478063-845c5900-a4b2-11ea-9f41-23d6e5fa2cfb.png)

**Comment by hasan-ozbey** [comment]
Should it be working though? 

This is not a bug, currently it will work on posts only and I tend to keep it this way.

**Comment by s1-ranjan** [comment]
Yes, i was expecting to see the maths codes in every location.. without showing up those scary codes... :)

**Comment by hasan-ozbey** [comment]
Well, it will cost you load time and will look ugly. Rendering math in every single post excerpt sounds more scary than the code itself - we can't truncate equations, and block elements should be converted to inline ones. 

But I wouldn't be worry about it. Since you're running some kind of math community platform, math geeks will see the equation through these codes. 😉

Another option might be forking of the excerpts extension and hiding math blocks completeley - or simply, don't use that extension?

I'm open to suggestions but can't promise anything...

**Comment by hasan-ozbey** [comment]
Check out 1.0.0
